### ISSUE TITLE
Matching bug

### ISSUE THREAD

**Issue by theRealPadster** [Florry/spicetify-playlist-filter#1]
If I search for "rel", it doesn't find "Release Radar", but if I search for "rad", it does. Capitalizations doesn't make a difference. 
![image](https://user-images.githubusercontent.com/1565883/155549709-b0e45a38-0912-485e-a46e-59c87d044bab.png)
![image](https://user-images.githubusercontent.com/1565883/155549747-73522c94-df1c-4479-8a7c-309dc20d49be.png)

**Comment by Florry** [comment]
oh thanks for pointing this out. It looks like it's because you have the "made for you" feature enabled, the first search result ends up underneath the filter box (you can see the background color of the matched letters slightly underneath it), I will fix!
I should also fix the styling so it works better with custom themes 😅

**Comment by Florry** [comment]
Fixed the issue in https://github.com/Florry/spicetify-playlist-filter/pull/2 
I also removed a lot of the spotify divs that were originally copied from the vanilla playlist list, simplifying the html, since it was causing more hassle than good. I'm aware this might cause some problems with custom themes (if they follow the structure of the vanilla playlist list as css selectors) but the "important" classes are still used (such as playlist list items). I tested the themes on the marketplace and they seem to work pretty well. And I also updated the colors to be transparent / transparent highlights so they work on any theme. Could you test with your theme and see how it looks? 

Edit: woops, forgot to build the files, that is coming up 😅 
Edit: fixed

**Comment by theRealPadster** [comment]
Thanks! Works now. For some reason I have a white square in the bottom corner though. 
![image](https://user-images.githubusercontent.com/1565883/155617468-eab61e81-6291-4009-9778-dfcda530a62f.png)

**Comment by theRealPadster** [comment]
It goes away when I disable the `overflow: scroll` on the ul...
![image](https://user-images.githubusercontent.com/1565883/155617746-bde6dba4-88b9-447f-8114-5fff59e21ec3.png)

**Comment by Florry** [comment]
Oh, does it work if you set overflow to auto? If it does I'll update the extension with that when I have time as doesn't break the scrolling, if not, do you have a link to the theme you're using so I can try it out and see if I can fix it?

**Comment by theRealPadster** [comment]
`overflow: auto` does fix it 👍

**Comment by Florry** [comment]
ah nice! I've updated the extension https://github.com/Florry/spicetify-playlist-filter/commit/ea2b147a55bd691e71e9228e6cc52511bb2875c2 
let me know if you find any other issues 🙂
